# Generated by Django 4.2 on 2023-05-03 05:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0002_alter_patients_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispense',
            name='dispense_quantity',
            field=models.PositiveIntegerField(default='1', null=True, verbose_name='soni'),
        ),
        migrations.AlterField(
            model_name='dispense',
            name='drug_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pharmacy.stock', verbose_name='dori_id'),
        ),
        migrations.AlterField(
            model_name='dispense',
            name='patient_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pharmacy.patients', verbose_name='bemor_id'),
        ),
        migrations.AlterField(
            model_name='patientfeedback',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='yaratilgan sana'),
        ),
        migrations.AlterField(
            model_name='patientfeedback',
            name='feedback',
            field=models.TextField(null=True, verbose_name='xabar'),
        ),
        migrations.AlterField(
            model_name='patientfeedback',
            name='patient_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacy.patients', verbose_name='bemor_id'),
        ),
        migrations.AlterField(
            model_name='patientfeedback',
            name='pharmacist_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pharmacy.pharmacist', verbose_name='farmaseftika_id'),
        ),
        migrations.AlterField(
            model_name='patientfeedback',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='yangilangan sana'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pharmacy.category', verbose_name='turkum'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='drug_color',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='dori_rangi'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='drug_description',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='dori_haqida'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='drug_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='dori_nomi'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='drug_pic',
            field=models.ImageField(blank=True, default='images2.png', null=True, upload_to='', verbose_name='dori_rasmi'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='drug_shape',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name="dori Ko'rinishi"),
        ),
        migrations.AlterField(
            model_name='stock',
            name='drug_strength',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='dori tasiri'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='yangilangan_sana'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='manufacture',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ishlab chiqaruvchi'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='quantity',
            field=models.IntegerField(blank=True, default='0', null=True, verbose_name='soni'),
        ),
    ]
